startFadeIn=5:30
endFadeIn=6:00
startFadeOut=17:50
endFadeOut=18:40
blend=alpha
rotate=true
axis=0.0 -1.0 0.0
source=./cloud10.png
biomes=taiga old_growth_pine_taiga old_growth_spruce_taiga snowy_taiga snowy_slopes frozen_peaks jagged_peaks grove snowy_plains frozen_river
transition=10